### ISSUE TITLE
Code Enhancement: Split the Main.hs into separate hs files for each simulation

### ISSUE THREAD

**Issue by vandan-revanur** [mkDoku/molecularDynamics#8]
The `Main.hs` at the moment is quite big (~500 lines), which is quite overwhelming to understand what is happening.

I tried to split the `Main.hs` and put the respective functions into separate .hs files like:

```
Simulation_1.hs
Simulation_2.hs
Simulation_3.hs
Simulation_4.hs
Helpers.hs
```

I put these in the src folder. 
However, I have trouble importing these into the `Main.hs.` 
I get an Intellisense error like: No module `Simulation_1.hs` found. 

Perhaps I am missing something. Could you either guide me in doing this or perhaps add it yourself?

**Comment by mkDoku** [comment]
Hi, there!

Without seeing your code, it is hard to see what went wrong. (In the future, feel free to create a branch named 'feature/short_name_for_issue', which should be based on the branch 'develop' so that I can have a look at your code).

In general, _Simulations_1.hs_ should be found if it is placed inside of **src/**.

Maybe something went wrong in export/importing the module.

The header in _Main.hs_ should look something like this:

```haskell
module Main where

import Simulation_1
```

and your header in _Simulation_1.hs_ like this:

```haskell
module Simulation_1 where

import Helpers
```

To help you out I created the branch [feature/split_main](https://github.com/mkDoku/molecularDynamics/tree/feature/split_main). Here you can see how I moved all functions into _Helpers.hs_ (first commit) and later all specific functions for Newton and Verlet simulations into different files. This changes will not be merged into the main branch, because the idea of this repository was to keep the code in sync with the blog post.

Hopefully, this helps. If not, do not hesitate to ask hear again.
When all your questions are answered I would like to close this issue.

**Comment by vandan-revanur** [comment]
Thanks for the detailed explanation. @mkDoku
I was missing to write `module Simulation_1 where ` inside of Simulation_1.hs
Also I guess one must use the capital letter for .hs files. 

Can you merge the [feature/split_main](https://github.com/mkDoku/molecularDynamics/tree/feature/split_main) with the master?

**Comment by mkDoku** [comment]
Sorry for answering so late, but I would like to keep changes to the main branch as minimal as possible, because changes there would require changes in the according [blog post](https://mkdoku.github.io/posts/2021-06-19-molecular-dynamics.html).
